---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: "12.1.2"

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-15.04
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: freebsd-9.3
  - name: freebsd-10.2
  - name: fedora-23
  - name: debian-8.2
  - name: debian-7.9
  - name: debian-6.0.10
  - name: opensuse-13.2

suites:
  # this tests basic functionality
  - name: default
    run_list:
      - recipe[unit::default]
    attributes:
  # this tests that we can run inside an LWRP
  - name: lwrp
    run_list:
      - recipe[unit::lwrp]
    attributes:
  # this tests that we can run inside a resource
  - name: resource
    run_list:
      - recipe[unit::resource]
    attributes:
  # this tests that we run correctly at compile-time
  - name: render
    run_list:
      - recipe[unit::render]
    attributes:
